
require('dotenv').config();

const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const bodyParser = require('body-parser');
const backupRoutes = require('./backupRoutes'); // Importar las rutas de respaldo

// Crear la aplicación Express
const app = express();
const port = process.env.PORT || 5000;

// Middlewares
app.use(cors());
app.use(bodyParser.json());

// Conectar a MongoDB Atlas
const uri = 'mongodb+srv://carlos123:carlos123@cluster0.zldjw7s.mongodb.net/smartstep?retryWrites=true&w=majority&ssl=true';
mongoose.connect(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
    tlsAllowInvalidCertificates: false,
    tlsAllowInvalidHostnames: false
  })
  .then(() => console.log('MongoDB database connection established successfully'))
  .catch(err => console.error('MongoDB connection error:', err));

// Definir el esquema y modelo de usuario
const userSchema = new mongoose.Schema({
  nombre: { type: String, required: true },
  apellido: { type: String, required: true },
  email: { type: String, required: true },
  password: { type: String, required: true },
  isAdmin: { type: Boolean, default: false }, // Agrega esta línea
  sessionActive: { type: Boolean, default: false } // Campo para estado de sesión
});

const User = mongoose.model('User', userSchema);

// Función para cifrar la contraseña con el método de cifrado César
function encryptPassword(password) {
  const shift = 5;
  let encrypted = '';

  for (let i = 0; i < password.length; i++) {
    let charCode = password.charCodeAt(i);

    if (charCode >= 65 && charCode <= 90) {
      // Uppercase letters
      charCode = ((charCode - 65 + shift) % 26) + 65;
    } else if (charCode >= 97 && charCode <= 122) {
      // Lowercase letters
      charCode = ((charCode - 97 + shift) % 26) + 97;
    }

    encrypted += String.fromCharCode(charCode);
  }

  return encrypted;
}

// Función para descifrar la contraseña cifrada con el método de cifrado César
function decryptPassword(encryptedPassword) {
  const shift = 5;
  let decrypted = '';

  for (let i = 0; i < encryptedPassword.length; i++) {
    let charCode = encryptedPassword.charCodeAt(i);

    if (charCode >= 65 && charCode <= 90) {
      // Uppercase letters
      charCode = ((charCode - 65 - shift + 26) % 26) + 65;
    } else if (charCode >= 97 && charCode <= 122) {
      // Lowercase letters
      charCode = ((charCode - 97 - shift + 26) % 26) + 97;
    }

    decrypted += String.fromCharCode(charCode);
  }

  return decrypted;
}
//register
app.post('/register', async (req, res) => {
  const { nombre, apellido, email, password } = req.body;

  try {
    const encryptedPassword = encryptPassword(password); // Cifrar la contraseña
    const newUser = new User({ nombre, apellido, email, password: encryptedPassword });
    await newUser.save();
    
    // Verificar que newUser._id está presente antes de enviarlo
    if (newUser._id) {
      console.log('User ID generated by MongoDB:', newUser._id);
    } else {
      console.error('Failed to generate user ID');
    }
    
    res.status(201).json({
      message: 'User registered successfully',
      id_usuario: newUser._id, // Devolver el ID del usuario creado
      name: newUser.nombre
    });
  } catch (error) {
    console.error('Error saving user:', error);
    res.status(500).json({ message: 'Server error' });
  }
});


// Ruta de inicio de sesión
app.post('/login', async (req, res) => {
  const { email, password } = req.body;
  try {
    // Buscar al usuario por correo electrónico
    const user = await User.findOne({ email });
    if (!user) {
      return res.status(400).json({ message: 'Usuario no encontrado' });
    }

    // Verificar la contraseña (desencriptar y comparar)
    const isPasswordValid = decryptPassword(user.password) === password;
    if (!isPasswordValid) {
      return res.status(400).json({ message: 'Contraseña incorrecta' });
    }

    // Actualizar el estado de sesión activa
    user.sessionActive = true;
    await user.save();

    // Devolver la respuesta con los datos del usuario
    res.status(200).json({
      message: 'Inicio de sesión exitoso',
      id_usuario: user._id,
      name: user.nombre,
      isAdmin: user.isAdmin
    });

    console.log(`Usuario ${user.nombre} ha iniciado sesión con ID: ${user._id}`); // Mostrar el ID del usuario en la consola
  } catch (error) {
    console.error('Error durante el inicio de sesión:', error);
    res.status(500).json({ message: 'Error del servidor' });
  }
});

app.post('/api/perfil', (req, res) => {
  const { nombre, fecha, altura, peso } = req.body;
  
  if (!nombre || !fecha || !altura || !peso) {
    return res.status(400).json({ message: 'Todos los campos son obligatorios' });
  }

  console.log(`Nombre: ${nombre}, Fecha: ${fecha}, Altura: ${altura}, Peso: ${peso}`);
  
  res.status(200).json({ message: 'Perfil actualizado correctamente' });
});

app.listen(5000, () => {
  console.log('Servidor corriendo en el puerto 5000');
});


app.listen(5000, () => {
  console.log('Servidor corriendo en puerto 5000');
});
// Ruta para verificar el estado de sesión
app.get('/check-session', async (req, res) => {
  const { email } = req.query;

  try {
    const user = await User.findOne({ email });
    if (!user) {
      return res.status(400).json({ message: 'Usuario no encontrado' });
    }

    // Verificar el estado de sesión
    res.status(200).json({
      sessionActive: user.sessionActive,
      id_usuario: user._id
    });

    console.log(`Estado de sesión para el usuario ${user.nombre}: ${user.sessionActive ? 'Activa' : 'Inactiva'}`); // Mostrar el estado de sesión en la consola
  } catch (error) {
    console.error('Error al verificar el estado de sesión:', error);
    res.status(500).json({ message: 'Error del servidor' });
  }
});

// Ruta para cerrar sesión
app.post('/logout', async (req, res) => {
  const { email } = req.body;

  try {
    const user = await User.findOne({ email });
    if (!user) {
      return res.status(400).json({ message: 'Usuario no encontrado' });
    }

    // Actualizar el estado de sesión inactiva
    user.sessionActive = false;
    await user.save();

    res.status(200).json({ message: 'Sesión cerrada con éxito' });

    console.log(`Usuario ${user.nombre} ha cerrado sesión`); // Mostrar el ID del usuario en la consola
  } catch (error) {
    console.error('Error durante el cierre de sesión:', error);
    res.status(500).json({ message: 'Error del servidor' });
  }
});

// Ruta para restablecimiento de contraseña
app.post('/reset-password', async (req, res) => {
  const { email, newPassword } = req.body;
  if (!email || !newPassword) {
    return res.status(400).json({ message: 'Correo electrónico y nueva contraseña son requeridos' });
  }

  try {
    const encryptedPassword = encryptPassword(newPassword); // Cifrar la nueva contraseña

    const result = await User.updateOne(
      { email }, // Encontrar al usuario por correo electrónico
      { $set: { password: encryptedPassword } } // Actualizar la contraseña
    );

    if (result.modifiedCount > 0) {
      res.status(200).json({ message: 'Contraseña actualizada con éxito' });
    } else {
      res.status(400).json({ message: 'No se pudo actualizar la contraseña. Verifique el correo electrónico.' });
    }
  } catch (error) {
    console.error('Error al actualizar la contraseña:', error);
    res.status(500).json({ message: 'Error del servidor' });
  }
});

// Usar las rutas de respaldo
app.use('/admin', backupRoutes); // Usa la ruta para las solicitudes de respaldo

// Iniciar el servidor
app.listen(port, () => {
  console.log(`Server is running on port: ${port}`);
});
